name: Build and Test

on:
  pull_request:
  push:
    branches: [main, develop]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  run:
    name: Run
    #    a uses: IngSoft-DA2/workflows/.github/workflows/reusable-build-test.yml@self-hosted-runner
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-build-test.yml@main
    permissions: write-all
    with:
      solution-name: backend/Obligatorio.sln
